theme: jekyll-theme-cayman
title: SwiftGuard
name: SwiftGuard
show_downloads: false
baseurl: "/SwiftGuard-Website"
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: compressed
stylesheets:
  - "/SwiftGuard-Website/assets/css/style.css"
